* debian/postinst: fix POSIX compatibilty. * debian/postinst: fix semantical error (exit only affects the subshell, not   the maintainerscript). * switch to the new dh implementation of debhelper 7.

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -3,13 +3,14 @@
 #DEBHELPER#
 # copied from ttf-bitstream-vera package
 
-if [ "$1" = configure -a -x /usr/bin/fc-cache ]
-then
+if [ "$1" = configure ] && [ -x /usr/bin/fc-cache ]; then
 	echo -n "Regenerating fonts cache... "
 
-	HOME=/root fc-cache -f -v 1>/var/log/fontconfig.log 2>&1 || \
-	(echo "failed; see /var/log/fontconfig.log for more information."; \
-	exit 1)
-
-	echo "done."
+	HOME=/root fc-cache -f -v 1>/var/log/fontconfig.log 2>&1
+	if [ "$?" -eq 0 ]; then
+		echo "done."
+	else
+		echo "failed; see /var/log/fontconfig.log for more information."
+		exit 1
+	fi
 fi
